# fly.toml app configuration file generated for emoguchi-backend on 2025-07-22T03:32:24+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'emoguchi-backend'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'
  PYTHONUNBUFFERED = '1'
  STORAGE_TYPE = 's3'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/v1/solo/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
